# Generated by Django 5.0.9 on 2026-09-24 12:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookedProductionYieldLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('REVIEWED', 'Reviewed')], default='OPEN', max_length=12)),
                ('record_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='record date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('type_of_product', models.CharField(max_length=150, verbose_name='type of product')),
                ('raw_lot_number', models.CharField(max_length=100, verbose_name='raw lot number')),
                ('finished_lot_number', models.CharField(max_length=100, verbose_name='finished lot number')),
                ('date_out_of_oven', models.DateField(default=django.utils.timezone.localdate, verbose_name='date out of oven')),
                ('date_packaged', models.DateField(default=django.utils.timezone.localdate, verbose_name='date packaged')),
                ('date_in_hot_room', models.DateField(blank=True, null=True, verbose_name='date in hot room')),
                ('date_in_hot_room_na', models.BooleanField(default=False, verbose_name='N/A')),
                ('date_out_hot_room', models.DateField(blank=True, null=True, verbose_name='date out hot room')),
                ('date_out_hot_room_na', models.BooleanField(default=False, verbose_name='N/A')),
                ('combos_used', models.PositiveIntegerField(default=0, verbose_name='combos used')),
                ('combo_lids_used', models.PositiveIntegerField(default=0, verbose_name='combo lids used')),
                ('combo_liners_used', models.PositiveIntegerField(default=0, verbose_name='combo liners used')),
                ('labels_used', models.PositiveIntegerField(default=0, verbose_name='labels used')),
                ('boxes_used', models.PositiveIntegerField(default=0, verbose_name='boxes used')),
                ('box_liners_used', models.PositiveIntegerField(default=0, verbose_name='box liners used')),
                ('waste_weight_lbs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='waste weight (lbs)')),
                ('yield_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Entered/confirmed by the user; verified by the supervisor on review.', max_digits=6, null=True, verbose_name='yield %')),
                ('notes', models.TextField(blank=True, help_text='Open narrative — anything not captured above.', verbose_name='notes')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cooked Production Yield Log',
                'verbose_name_plural': 'Cooked Production Yield Logs',
                'ordering': ['-record_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeTaskLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_initials', models.CharField(max_length=6, verbose_name='initials')),
                ('task', models.CharField(max_length=150, verbose_name='task')),
                ('time_to_complete_hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='time to complete (hours)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('yield_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_tasks', to='brc_forms.cookedproductionyieldlog')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FieldNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(help_text='Which field on the record this note refers to.', max_length=100)),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackagingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_description', models.CharField(max_length=100, verbose_name='packaging description')),
                ('size_description', models.CharField(max_length=150, verbose_name='size')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='weight (lbs)')),
                ('piece_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='piece count')),
                ('piece_count_na', models.BooleanField(default=False, verbose_name='N/A')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('yield_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_lines', to='brc_forms.cookedproductionyieldlog')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
