# Generated by Django 5.0.9 on 2026-09-24 12:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='code')),
                ('name_en', models.CharField(max_length=150, verbose_name='name (English)')),
                ('name_es', models.CharField(blank=True, max_length=150, verbose_name='name (Spanish)')),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium')], default='MEDIUM', max_length=10)),
                ('is_implemented', models.BooleanField(default=False, help_text="Whether this form's data-entry screens exist yet in the app.")),
                ('url_name', models.CharField(blank=True, help_text="URL namespace:name to the form's list view, once implemented.", max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('initials', models.CharField(blank=True, help_text="Used to stamp entries on multi-user forms, e.g. 'JJS'.", max_length=6, verbose_name='initials')),
                ('is_administrator', models.BooleanField(default=False, help_text='Can manage users and per-form role assignments and predefined values.', verbose_name='administrator')),
                ('must_change_password', models.BooleanField(default=True, help_text='Forces a password change on next login. Set automatically for new accounts.', verbose_name='must change password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FormRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'User (enters data)'), ('SUPERVISOR', 'Supervisor (reviews & approves)'), ('AUDITOR', 'Auditor (read-only)')], max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_roles', to=settings.AUTH_USER_MODEL)),
                ('form_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='accounts.formtype')),
            ],
        ),
        migrations.CreateModel(
            name='PredefinedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.SlugField(help_text="Which dropdown this belongs to, e.g. 'product_type'.")),
                ('value_en', models.CharField(max_length=200)),
                ('value_es', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('form_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_values', to='accounts.formtype')),
            ],
            options={
                'ordering': ['field_key', 'sort_order', 'value_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='formroleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'form_type'), name='one_role_per_user_per_form'),
        ),
        migrations.AddConstraint(
            model_name='predefinedvalue',
            constraint=models.UniqueConstraint(fields=('form_type', 'field_key', 'value_en'), name='unique_value_per_field'),
        ),
    ]
